INSERT INTO TIPO_COMPROMISSO (ID, DESCRICAO) VALUES (1, "TIPO 1");
INSERT INTO TIPO_COMPROMISSO (ID, DESCRICAO) VALUES (2, "TIPO 2");
INSERT INTO TIPO_COMPROMISSO (ID, DESCRICAO) VALUES (3, "TIPO 3");
INSERT INTO TIPO_COMPROMISSO (ID, DESCRICAO) VALUES (4, "TIPO 4");
INSERT INTO TIPO_COMPROMISSO (ID, DESCRICAO) VALUES (5, "TIPO 5");
INSERT INTO TIPO_COMPROMISSO (ID, DESCRICAO) VALUES (6, "TIPO 6");
