INSERT INTO TIPO_COMPROMISSO (ID, DESCRICAO) VALUES (1, "Reunião");
INSERT INTO TIPO_COMPROMISSO (ID, DESCRICAO) VALUES (2, "Workshop");
INSERT INTO TIPO_COMPROMISSO (ID, DESCRICAO) VALUES (3, "Conference Call");
INSERT INTO TIPO_COMPROMISSO (ID, DESCRICAO) VALUES (4, "Treinamento");